apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  postgres-user: user
  postgres-password: password
  mariadb-user: user
  mariadb-password: password
  mariadb-root-password: rootpassword
  api-token: "mi_clave_secreta"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi